#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 23 10:53:11 2019

@author: tushar
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
N=int(input())
n=int(input())
p=float(input())

datapoints=np.random.binomial(n,p,N)
print(datapoints)
df=pd.DataFrame({'Data':datapoints})
df.to_csv('binomial_N_n_p.dat',index=False)

