#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  1 13:07:11 2019

@author: tushar
"""


import pandas as pd
import numpy as np
# Generate a DataFrame to hold the data
d= pd.DataFrame(columns = ['x1','x2','x3'])
numTrials = 100
d.x1 = np.random.randint(0,2,numTrials)
d.x2 = np.random.randint(0,2,numTrials)
d.x3 = np.random.randint(0,2,numTrials)
# print the DataFrame
#print(d)
s1=list(d.x1)
s2=list(d.x2)
s3=list(d.x3)
for i in range(len(s1)):
    s1[i]=s1[i]*50
for i in range(len(s1)):
    s2[i]=s2[i]*20
for i in range(len(s1)):
    s3[i]=s3[i]*10
#print(s1,s2,s3)
d=[]
for i in range(len(s1)):
    d.append((s1[i]+s2[i]+s3[i]))
print(sum(d)/len(d))
g=[]
for i in range(len(d)):
    if d[i]==60:
        g.append(d[i])
    if d[i]==30:
        g.append(d[i])
    if d[i]==70:
        g.append(d[i])
print(sum(g)/len(g))